name: mighty_lube
description: "A new Flutter project."
publish_to: 'none'
# NOTE:
# iOS App Store already has version 2.0.0, so both platforms are being
# moved to 2.0.1 to keep Android and iOS versions aligned.
# The current Android production version may still be older until the next
# Android release version 1.0.0 and build number 7
version: 2.0.2+9

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  password_strength_checker: ^1.2.4
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  dropdown_search: ^5.0.2
  badges: ^3.1.2
  intl: ^0.18.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.1.14
  photo_view: ^0.15.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/ML_Logo_square.png
  android_12:
    image: assets/ML_Logo_square.png
    icon_background_color: "#ffffff"
  
flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ML_Logo_square.png"
  adaptive_icon_background: "#ffffff"

flutter:
  config:
    enable-swift-package-manager: false
  uses-material-design: true
  assets:
     - assets/
     - assets/industrial/
     - assets/industrial/CC5 Chain (2)/
     - assets/industrial/CC5 Chain (2)/CLS (2)/
     - assets/industrial/CC5 Chain (2)/CLS (2)/MLCCL/
     - assets/industrial/CC5 Chain (2)/CLS (2)/OP40E/

     - assets/industrial/Caterpillar Drive ( 3 )/
     - assets/industrial/Caterpillar Drive ( 3 )/Conveyor Lubrication System (3)/
     - assets/industrial/Caterpillar Drive ( 3 )/Conveyor Lubrication System (3)/MLCEL/
     - assets/industrial/Caterpillar Drive ( 3 )/Conveyor Lubrication System (3)/OP40E/

     - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/
     - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/
     - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/0P41A/
     - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/OP48E/
     - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/9000INVL/
     - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Cleaning Solutions (2)/
     - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Monitor Systems (1)/

     - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/
     - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Lub. Systems (4)/
     - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Monitor Systems (2)/

     - assets/industrial/Flat Top (4)/
     - assets/industrial/Flat Top (4)/Conveyor Greaser Systems (1)/
     - assets/industrial/Flat Top (4)/Conveyor Greaser Systems (1)/OPCO300/
     - assets/industrial/Flat Top (4)/Conveyor Lub. Systems (3)/


     - assets/industrial/Free Carrier (2)/
     - assets/industrial/Free Carrier (2)/FR314/
     - assets/industrial/Free Carrier (2)/FR317/

     - assets/industrial/C Channel Overhead Or Inverted(6)/
     - assets/industrial/C Channel Overhead Or Inverted(6)/CCS/

     - assets/industrial/C Channel Overhead Or Inverted(6)/CGS/
     - assets/industrial/C Channel Overhead Or Inverted(6)/CGS/314/
     - assets/industrial/C Channel Overhead Or Inverted(6)/CGS/317/

     - assets/industrial/C Channel Overhead Or Inverted(6)/CLS/
     - assets/industrial/C Channel Overhead Or Inverted(6)/CLS/9000/
     - assets/industrial/C Channel Overhead Or Inverted(6)/CLS/Eseries/
     - assets/industrial/C Channel Overhead Or Inverted(6)/CLS/OP139A/


     - assets/industrial/FTL/
     - assets/industrial/FTL/CLS/
     - assets/industrial/FTL/CLS/MLFTL/
     - assets/industrial/FTL/CLS/OP40E/

     - assets/industrial/In Board Roller Chain(3)/
     - assets/industrial/In Board Roller Chain(3)/CGS/
     - assets/industrial/In Board Roller Chain(3)/CLS/


     - assets/industrial/OHP(20)/
     - assets/industrial/OHP(20)/CCS/
     - assets/industrial/OHP(20)/CCS/Mesurment/
     - assets/industrial/OHP(20)/CGS/
     - assets/industrial/OHP(20)/CLS/
#     - assets/industrial/OHP(20)/CLS/9000L/
     - assets/industrial/OHP(20)/CMS/

     - assets/industrial/PFO(16)/
     - assets/industrial/PFO(16)/CCS/
     - assets/industrial/PFO(16)/CGS/
     - assets/industrial/PFO(16)/CGS/314/
     - assets/industrial/PFO(16)/CGS/317/
     - assets/industrial/PFO(16)/CLS/
     - assets/industrial/PFO(16)/CLS/9000L/
     - assets/industrial/PFO(16)/CLS/E-Series/
     - assets/industrial/PFO(16)/CLS/I-Beam/
     - assets/industrial/PFO(16)/CLS/OP139A/
     - assets/industrial/PFO(16)/CMS/


     - assets/Protein/
     - assets/Protein/FGC/
     - assets/Protein/FGL/


