name: mighty_lube
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  password_strength_checker: ^1.2.4
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  dropdown_search: ^5.0.2
  badges: ^3.1.2
  intl: ^0.18.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/ML_Logo_square.png
  android_12:
    image: assets/ML_Logo_square.png
    icon_background_color: "#ffffff"
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/ML_Logo_square.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/countries.json
    - assets/ML_Logo-w-tag-vector.svg
    - assets/WhiteML_Logo-w-tag-vector.svg

    - assets/FGLM.png
    - assets/FGCO.png

    - assets/Industrial.png
    - assets/Protein.png
    - assets/Technician.png

    - assets/industrial/Title.png
    - assets/industrial/CC5 Chain (2)/CC5 Chain (2).png
    - assets/industrial/Free Carrier (2)/Title.png
   
    - assets/industrial/FreeRail.png
    - assets/industrial/inFloor.png
    - assets/industrial/inBoard.png
    - assets/industrial/OverHeadPower.png

    - assets/industrial/CC5 Chain (2)/CLS (2)/CLS.png
    - assets/industrial/CC5 Chain (2)/CLS (2)/MLCCL.png
    - assets/industrial/CC5 Chain (2)/CLS (2)/OP-40E.png

    - assets/industrial/Chain On Edge Drag Line (3)/Conveyor Lub. Systems/Title.png
    - assets/industrial/Chain On Edge Drag Line (3)/Conveyor Lub. Systems/CDL.png
    - assets/industrial/Chain On Edge Drag Line (3)/Conveyor Lub. Systems/MLCEL.png

    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Cleaning Solutions (2)/Title.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/Title.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Monitor Systems (1)/title.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Cleaning Solutions (2)/8074-B.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Cleaning Solutions (2)/UN91.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/9000INVL.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/OP-41A.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/OP-48E.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Monitor Systems (1)/Multi Line.png

    - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Lub. Systems (4)/2100L.png
    - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Lub. Systems (4)/9000L.png
    - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Lub. Systems (4)/OP-41A.png
    - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Lub. Systems (4)/OP-48E.png
    - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Lub. Systems (4)/title.png
    - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Monitor Systems (2)/Multi Line.png
    - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Monitor Systems (2)/Portable Multi Line.png
    - assets/industrial/Enclosed Track Overhead Power Only and P&F (10)/Conveyor Monitor Systems (2)/Title.png

    - assets/industrial/Flat Top (4)/flat-top.png
    - assets/industrial/Flat Top (4)/Conveyor Greaser Systems (1)/OPCP 300.png


    - assets/industrial/Free Carrier (2)/FR314.png
    - assets/industrial/Free Carrier (2)/FR317.png


    - assets/industrial/OHPRLB(20)/CCS/CCS.png
    - assets/industrial/OHPRLB(20)/CCS/300I.png
    - assets/industrial/OHPRLB(20)/CCS/LBCBS.png
    - assets/industrial/OHPRLB(20)/CCS/OEB.png
    - assets/industrial/OHPRLB(20)/CCS/OP8.png
    - assets/industrial/OHPRLB(20)/CCS/OP8NP.png
    - assets/industrial/OHPRLB(20)/CCS/OP13.png
    - assets/industrial/OHPRLB(20)/CCS/OP55.png
    - assets/industrial/OHPRLB(20)/CCS/YCB.png

    - assets/industrial/OHPRLB(20)/CGS/CGS.png

    - assets/industrial/OHPRLB(20)/CLS/CLS.png
    - assets/industrial/OHPRLB(20)/CLS/2100L.png
    - assets/industrial/OHPRLB(20)/CLS/9000L.png
    - assets/industrial/OHPRLB(20)/CLS/CDL.png
    - assets/industrial/OHPRLB(20)/CLS/ES.png
    - assets/industrial/OHPRLB(20)/CLS/OP4A.png
    - assets/industrial/OHPRLB(20)/CLS/OP52.png
    - assets/industrial/OHPRLB(20)/CLS/OP139A.png

    - assets/industrial/PFOOI(17)/CMS/CMS.png
    - assets/industrial/PFOOI(17)/CMS/MLAIO.png
    - assets/industrial/PFOOI(17)/CMS/PMLMS.png
    - assets/industrial/PFOOI(17)/CMS/PMMS.png
    - assets/industrial/PFOOI(17)/CMS/SLMLMS.png

    - assets/industrial/IBRC(3)/CLS.png
    - assets/industrial/IBRC(3)/CGS.png
    - assets/industrial/IBRC(3)/MLRFC.png
    - assets/industrial/PFOOI(17)/CCS/300I.png
    - assets/industrial/PFOOI(17)/CCS/CCS.png
    - assets/industrial/PFOOI(17)/CCS/OP8.png
    - assets/industrial/PFOOI(17)/CCS/OP8NP.png
    - assets/industrial/PFOOI(17)/CGS/CGS.png
    - assets/industrial/PFOOI(17)/CGS/FR314.png
    - assets/industrial/PFOOI(17)/CGS/FR317.png
    - assets/industrial/PFOOI(17)/CGS/GPC.png
    - assets/industrial/PFOOI(17)/CLS/CLS.png
    - assets/industrial/PFOOI(17)/CLS/9000L.png
    - assets/industrial/PFOOI(17)/CLS/9000LFCCCL.png
    - assets/industrial/PFOOI(17)/CLS/9000LTCL.png
    - assets/industrial/PFOOI(17)/CLS/CDL.png
    - assets/industrial/PFOOI(17)/CLS/ES.png
    - assets/industrial/PFOOI(17)/CLS/OP55.png
    - assets/industrial/PFOOI(17)/CLS/OP139A.png