name: mighty_lube
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  password_strength_checker: ^1.2.4
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  dropdown_search: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/countries.json
    - assets/ML_Logo-w-tag-vector.svg
    - assets/WhiteML_Logo-w-tag-vector.svg

    - assets/FGLM.png
    - assets/FGCO.png

    - assets/Industrial.png
    - assets/Protein.png
    - assets/Technician.png