name: mighty_lube
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  password_strength_checker: ^1.2.4
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  dropdown_search: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/countries.json
    - assets/ML_Logo-w-tag-vector.svg
    - assets/WhiteML_Logo-w-tag-vector.svg

    - assets/FGLM.png
    - assets/FGCO.png

    - assets/Industrial.png
    - assets/Protein.png
    - assets/Technician.png

    - assets/industrial/Title.png
    - assets/industrial/CC5 Chain (2)/CC5 Chain (2).png
    - assets/industrial/Free Carrier (2)/Title.png
    - assets/industrial/Flat Top (4)/flat-top.png
    - assets/industrial/FreeRail.png
    - assets/industrial/inFloor.png
    - assets/industrial/inBoard.png
    - assets/industrial/OverHeadPower.png
    - assets/industrial/CC5 Chain (2)/CLS (2)/CLS.png
    - assets/industrial/CC5 Chain (2)/CLS (2)/MLCCL.png
    - assets/industrial/CC5 Chain (2)/CLS (2)/OP-40E.png
    - assets/industrial/Chain On Edge Drag Line (3)/Conveyor Lub. Systems/Title.png
    - assets/industrial/Chain On Edge Drag Line (3)/Conveyor Lub. Systems/CDL.png
    - assets/industrial/Chain On Edge Drag Line (3)/Conveyor Lub. Systems/MLCEL.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Cleaning Solutions (2)/Title.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/Title.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Monitor Systems (1)/title.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Cleaning Solutions (2)/8074-B.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Cleaning Solutions (2)/UN91.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/9000INVL.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/OP-41A.png
    - assets/industrial/Enclosed Track Inverted Power Only and P&F (8)/Conveyor Lub. Systems (3)/OP-48E.png



    - assets/industrial/Free Carrier (2)/FR314.png
    - assets/industrial/Free Carrier (2)/FR317.png

    - assets/industrial/IBRC(3)/CLS.png
    - assets/industrial/IBRC(3)/CGS.png
    - assets/industrial/IBRC(3)/MLRFC.png